version: "3"

services:
  duplicati:
    build:
      context: "."
    container_name: "duplicati"
    hostname: "${HOSTNAME:-duplicati}"
    environment:
      - "PUID=0"
      - "PGID=0"
      - "TZ=Europe/London"
    ports:
      - "8200:8200"
    restart: "always"
    volumes:
      - "/dev/rtc:/dev/rtc:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "config:/config"
      - "data:/data"
      - "source:/source"
      - "shared_backups:/backups"

volumes:
  config:
  data:
  source:
  shared_backups:
    external: true

networks:
  default:
    external:
      name: "shared_network"
